version: '3'
services:
  auth:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/home/code
      - auth_files:/home/code/files
    environment:
      - ENV=${ENV}
  cbns:
    build: ./cbns
    ports:
      - "8088:8080"

volumes:
  auth_files:
