version: '3'
services:
  auth:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/home/code
      - auth_files:/home/code/files
    environment:
      - ENV=${ENV}
  redis:
    image: redis
    ports:
      - "6379:6379"
  cbns:
    build: ./cbns
    ports:
      - "8088:8080"
  cbns_update:
    build: ./cbns_globalUpdate

volumes:
  auth_files: