version: '3'
services:
  auth:
    build: .
    ports:
      - "${PORT}:8085"
    volumes:
      - .:/home/code
    environment:
      - ENV=${ENV}
  redis:
    image: redis
    ports:
      - "6379:6379"
  cbns:
    build: ./cbns
    ports:
      - "8087:8087"